const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('#nav');toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));

const form=document.querySelector('#contact-form');const status=document.querySelector('#form-status');const submit=form?.querySelector('button[type="submit"]');
form?.addEventListener('submit',async(e)=>{e.preventDefault();if(!form.reportValidity())return;submit.disabled=true;const old=submit.firstChild.textContent;submit.firstChild.textContent='Versturen… ';status.textContent='';
  const data=Object.fromEntries(new FormData(form).entries());
  try{const res=await fetch('/.netlify/functions/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'Verzenden mislukt');form.reset();status.textContent='Bedankt! Je bericht is verzonden. Ik neem zo snel mogelijk contact met je op.'}
  catch(err){status.textContent='Het versturen is niet gelukt. Probeer het later opnieuw.'}
  finally{submit.disabled=false;submit.firstChild.textContent=old}
});

// Huhta screenshot gallery
(()=>{const trigger=document.querySelector('.huhta-gallery-trigger'),box=document.querySelector('#huhta-lightbox');if(!trigger||!box)return;const img=box.querySelector('img'),count=box.querySelector('.lightbox-count'),close=box.querySelector('.lightbox-close'),prev=box.querySelector('.lightbox-prev'),next=box.querySelector('.lightbox-next');const shots=Array.from({length:6},(_,i)=>'/huhta-'+(i+1)+'.webp');let index=0,touchX=0;const show=n=>{index=(n+shots.length)%shots.length;img.src=shots[index];img.alt='Huhta screenshot '+(index+1);count.textContent=(index+1)+' / '+shots.length};const open=()=>{show(0);box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.classList.add('lightbox-open');close.focus()};const shut=()=>{box.classList.remove('open');box.setAttribute('aria-hidden','true');document.body.classList.remove('lightbox-open');trigger.focus()};trigger.addEventListener('click',open);document.querySelectorAll('.gallery-entry-arrow').forEach(btn=>btn.addEventListener('click',open));close.addEventListener('click',shut);prev.addEventListener('click',()=>show(index-1));next.addEventListener('click',()=>show(index+1));box.addEventListener('click',e=>{if(e.target===box)shut()});document.addEventListener('keydown',e=>{if(!box.classList.contains('open'))return;if(e.key==='Escape')shut();if(e.key==='ArrowLeft')show(index-1);if(e.key==='ArrowRight')show(index+1)});box.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX},{passive:true});box.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>45)show(index+(dx<0?1:-1))},{passive:true});shots.forEach(src=>{const p=new Image();p.src=src})})();
